### ISSUE TITLE
IOS Builds - not appearing in Test Flight App

### ISSUE THREAD

**Issue by Nova8** [limelight-stream/limelight-ios#51]
Hi guys & girls, can't seem to see the builds in the Test Flight App online and in the app. Do I have to added it manually?

**Comment by sigboe** [comment]
@Nova8 If you has been added to the beta program after the previous beta release was published, you will have to wait until the next beta release before you will see anything in Test Flight. 

Don't worry, two pull requests, and a large number of improvements have been added since the last beta build so I do not presume you will have to wait for an eternity.

**Comment by dwaxemberg** [comment]
You need to wait until we push a new build. Should be soon.
