### ISSUE TITLE
Limelight keep crashing while connecting

### ISSUE THREAD

**Issue by iamfalan** [limelight-stream/limelight-ios#54]
Today I just upgrade limelight to 0.3.2 and upgrade GFE TO 2.2.2 on my PC.
When I try to connect lime light keep crashing. i try to delete the app and re install but it wont work.
I try both on my ipad air 2 and iphone 5s, no work either

**Comment by dwaxemberg** [comment]
If it is crashing immediately when you launch the app then this is somewhat expected. You must completely remove and reinstall the app. If it crashes at some point in the app, then there is an issue.

Please reinstall the app using the new beta system (you should have received an email just now) so it will send me the crash report.

**Comment by iamfalan** [comment]
It's take a while after opening the app. Look like before it showing hosts list.
I reinstall the app with new beta system now.

On my other device (iphone 5s) never install limelight before. And it crashing everytime I add host.

**Comment by dwaxemberg** [comment]
It turns out for beta testing iTunes does not provide me with the crash logs. Can you please send them to me? Here are instructions on how to get the logs: https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/AppDistributionGuide/TestingYouriOSApp/TestingYouriOSApp.html#//apple_ref/doc/uid/TP40012582-CH8-SW7

**Comment by iamfalan** [comment]
I check crashlog but cannot find limelight app's crash log.
Did you use limelight as your project's name?

**Comment by abattrick** [comment]
Mines seems to work pretty great except it doesn't load all my icons for games. I have 110 gamestream ready games not sure if it's to many icons.

**Comment by Doug-Luce** [comment]
It's crashing for me as well but not right at the start. It first makes a lot of copies of my computers running GFE. I have 3 GFE computers in the house and it will make 3-4 copies of them all until it crashes.

**Comment by PixelBurstHD** [comment]
Mine crashes as soon as I open it which is weird because it was working fine - I've even tried restoring the phone just in case it was a conflict, but even a fresh restore and fresh install of the latest and last available build of Limelight you just see the hosts screen for a split second then it's gone. 5C 8.1.2 Nvidia GeForce experience 2.2.3.0. 

I've tried doing as you suggested dwaxdemberg and uninstalling and reinstalling however I still get the same issue.

**Comment by abattrick** [comment]
Mine is working well for streaming all though the slider for quality doesn't work and the thumbnails only load like 5 or 6 thumbs out of my 110 compatible games. 

Good work so far though

**Comment by iamfalan** [comment]
What about this issue? Did I have to send some crashlog or something?

**Comment by iamfalan** [comment]
Mine can be played fine now with this work around,
i need to restart nvidia streaming service every time I start my pc.
Now it can be played but still annoyed byg.

**Comment by iamfalan** [comment]
Ok new version does not crash anymore. And does not need to restart nvidia streamer anymore. Good job guys
